### ISSUE TITLE
Incompatible with Spring Boot 2.2.x

### ISSUE THREAD

**Issue by priyansms** [jetty-project/jetty-reactive-httpclient#18] opened 2019-11-17 00:50 UTC
java.lang.AbstractMethodError: Receiver class org.eclipse.jetty.reactive.client.internal.ResponseListenerPublisher does not define or inherit an implementation of the resolved method abstract onContent(Lorg/eclipse/jetty/client/api/Response;Ljava/util/function/LongConsumer;Ljava/nio/ByteBuffer;Lorg/eclipse/jetty/util/Callback;)V of interface org.eclipse.jetty.client.api.Response$DemandedContentListener.
        at org.eclipse.jetty.client.ResponseNotifier.notifyContent(ResponseNotifier.java:155) ~[jetty-client-9.4.22.v20191022.jar:9.4.22.v20191022]
        at org.eclipse.jetty.client.ResponseNotifier.notifyContent(ResponseNotifier.java:146) ~[jetty-client-9.4.22.v20191022.jar:9.4.22.v20191022]

**Comment by sbordet** [comment] 2019-11-17 15:24
Duplicate of #17.

**Closed by sbordet** 2019-11-17 15:24 UTC
