### ISSUE TITLE
Post request not setting Auth Header Correctly When Using Digest Auth

### ISSUE THREAD

**Issue by prafsoni** [jetty-project/jetty-reactive-httpclient#59] opened 2021-06-22 16:17 UTC
Version: 1.1.9

When trying to upload a file to remote server with Digest Auth. After receiving the challenge request doesn't set correct auth headers. This causes the request to fail with 401. After some debugging found that in `AuthenticationProtocolHandler.AuthenticationListener`  the check !requestContent.isReproducible() is incorrectly calling `forwardSuccessComplete` before updating headers and trying again.

```java
  ContentProvider requestContent = request.getContent();
  if (requestContent != null && !requestContent.isReproducible())
  {
      if (LOG.isDebugEnabled())
          LOG.debug("Request content not reproducible for {}", request);
      forwardSuccessComplete(request, response);
      return;
  }

  try
  {
      Authentication.Result authnResult = authentication.authenticate(request, response, headerInfo, conversation);
      if (LOG.isDebugEnabled())
          LOG.debug("Authentication result {}", authnResult);
```

One approach I can think of is we can have a variant of `PublisherContent` where  `isReproducible()` returns `true`, idk this might be a bit contradicting reactive stream there might be a better/more correct approach to handle this. 

Is there a workaround for this? My current work around using jetty `send(<BufferedResponseListener>)` approach.

**Comment by sbordet** [comment] 2021-06-29 17:57
> After receiving the challenge request doesn't set correct auth headers.

What do you mean? The headers are correctly set.
Do you have an example/evidence of this?

> the check !requestContent.isReproducible() is incorrectly calling forwardSuccessComplete before updating headers and trying again.

If the content is not reproducible, then the request cannot be retried automatically by Jetty, so calling `forwardSuccessComplete()` is correct.

The correct solution would be to not send un-authenticated POST request with non-reproducible content that the server rejects.
If your digest authentication expires after a while, set up a timer and re-login with an idempotent request before it expires.

Alternatively, read the content into a `byte[]` or `String` (or other ways) so that it is reprodicible, and Jetty will retry automatically the request.

Any other solution is application dependent, because only the application knows how to handle the non-reproducible content.

**Comment by sbordet** [comment] 2022-02-15 18:16
Closing as addressed.

**Closed as completed by sbordet** 2022-02-15 18:16 UTC
