### ISSUE TITLE
Version for Jetty 12

### ISSUE THREAD

**Issue by poutsma** [jetty-project/jetty-reactive-httpclient#244] opened 2023-06-20 13:34 UTC
Hi,

I work on the Spring Framework, where we use `jetty-reactive-httpclient` as one of the options for providing HTTP connections to our `WebClient`. We are currently considering upgrading to Jetty 12 as part of our 6.1 branch, but noticed that a version of `jetty-reactive-httpclient` for Jetty 12 has not been released yet.

Is a `jetty-reactive-httpclient` for Jetty 12 forthcoming? And if so, could you please share your release schedule?

**Comment by sbordet** [comment] 2023-06-20 17:44
@poutsma the next major version of `jetty-reactive-httpclient` based on Jetty 12 will be available just after Jetty 12 is released.

The plan is for Jetty to be released within July, hopefully first half, and I think second half for `jetty-reactive-httpclient`.

**Comment by poutsma** [comment] 2023-06-21 08:00
@sbordet Thank you!

**Comment by lorban** [comment] 2023-07-11 09:00
See https://github.com/spring-projects/spring-framework/issues/30698#issuecomment-1600403774 for context.

**Comment by lorban** [comment] 2023-07-13 13:38
@poutsma We are the the process of actively adapting the Reactive Client to Jetty 12, and we're pretty much done making it almost identical to the Jetty 11 version.

But looking at how the Spring Framework uses jetty-reactive-httpclient we noticed the following that might be of importance to you:

In [JettyClientHttpConnector.execute()](https://github.com/spring-projects/spring-framework/blob/cc7f3101b79a2d51369d74783839654d0f996b54/spring-web/src/main/java/org/springframework/http/client/reactive/JettyClientHttpConnector.java#L128) you are basically transforming `org.eclipse.jetty.reactive.client.ContentChunk`s into `org.springframework.core.io.buffer.DataBuffer`s by using the [toDataBuffer()](https://github.com/spring-projects/spring-framework/blob/cc7f3101b79a2d51369d74783839654d0f996b54/spring-web/src/main/java/org/springframework/http/client/reactive/JettyClientHttpConnector.java#L136-L149) method that copies the buffer coming from Jetty into a freshly allocated Spring buffer.

This is all fine and dandy but the extra allocation and memory copy comes with an extra performance cost that we think could be eliminated. Jetty 12 introduced the [Content.Chunk](https://github.com/eclipse/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java#L462) interface (which extends [Retainable](https://github.com/eclipse/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Retainable.java#L49)) that is serendipitously similar to Spring's [PooledDataBuffer](https://github.com/spring-projects/spring-framework/blob/cc7f3101b79a2d51369d74783839654d0f996b54/spring-core/src/main/java/org/springframework/core/io/buffer/PooledDataBuffer.java#L26), both having `retain()` and `release()` methods with almost identical contracts.

So we were wondering if you would prefer to keep the Jetty 12 Reactive Client API as close as possible to the Jetty 11 version with the `ContentChunk` class that requires Spring to perform a copy, or would you rather have us change the API to expose the new `Retainable` `Content.Chunk`s so you could wrap those as Spring `PooledDataBuffer`s instead?

Please note that if you decide to go for the 2nd option, we're going to have to understand better how Spring manages the lifecycle of the `PooledDataBuffer`s as the way Jetty retains and releases its buffers would certainly require some adaptation, which could be done either in Jetty Reactive Client or in Spring Framework.

Let us know.
Thanks!

**Comment by sbordet** [comment] 2023-07-13 13:55
I just pushed the update to Jetty 12 to branch `4.0.x`, if you want to try it.

**Comment by poutsma** [comment] 2023-07-13 13:58
Hi @lorban, and thank you for getting in touch.

>So we were wondering if you would prefer to keep the Jetty 12 Reactive Client API as close as possible to the Jetty 11 version with the ContentChunk class that requires Spring to perform a copy, or would you rather have us change the API to expose the new Retainable...

It sounds like the new `Content.Chunk` approach is better in terms of memory usage, so I will attempt to use that, and adapt it to a `PooledDataBuffer` (used mainly to support Netty 4) or `CloseableDataBuffer` (introduced to support Netty 5).

**Comment by poutsma** [comment] 2023-07-13 14:00
> I just pushed the update to Jetty 12 to branch `4.0.x`, if you want to try it.

I am taking a short break after [today's release](https://spring.io/blog/2023/07/13/new-in-spring-6-1-restclient), but will get back to you when I return.

**Comment by lorban** [comment] 2023-07-13 14:43
@poutsma I'm also about to take some time off, so please also notify @sbordet when you're back working on this in case you're back first.

Thanks for your help!

**Comment by sbordet** [comment] 2023-07-14 19:01
@poutsma @jhoeller FYI I have release version 4.0.0.beta0 of this project for you to try out.

**Comment by poutsma** [comment] 2023-07-24 09:37
I have started working on the upgrade to 4.0 beta 0, but I am running into an issue where the chunk publisher given in `ReactiveRequest::response(BiFunction<ReactiveResponse,Publisher<Content.Chunk>,Publisher<T>>)` does not seem to have a complete signal.

Here is a sample that reproduces the issue. It does not use Spring, but does use Reactor.

```java
HttpClient httpClient = new HttpClient();
httpClient.start();
ReactiveRequest request = ReactiveRequest.newBuilder(httpClient, "https://example.org").build();

// Publisher<String> response = request.response(ReactiveResponse.Content.asString());

Publisher<String> response = request.response((reactiveResponse, chunkPublisher) -> {
	return Flux.from(chunkPublisher)
			.map(chunk -> {
				ByteBuffer byteBuffer = chunk.getByteBuffer();
				CharBuffer charBuffer = StandardCharsets.UTF_8.decode(byteBuffer);
				String s = charBuffer.toString();

				chunk.release();
				return s;
			})
			.doOnComplete(() -> System.out.println("ChunkPublisher complete"));

});
Flux.from(response)
		.doOnComplete(() -> System.out.println("Response complete"))
		.subscribe(System.out::println);
```

Neither of the two completion statements are printed. The interesting thing is that the commented out line does give me a result. The only difference I can out make between the two is that the `BufferingProcessor`—used by `ReactiveResponse.Content.asString`—stores the chunks before releasing them, whereas I release them immediately. Another difference is that `BufferingProcessor` is a reactive `Processor`, whereas I am returning a Flux instead.

Any ideas? I could very well be doing something wrong here, so please tell me if I did.

**Comment by sbordet** [comment] 2023-07-24 10:46
@poutsma the code should work.

Another difference is that we create the string from all the bytes, while in your case you may have a split UTF-8 sequence when you try to decode the bytes into a `CharBuffer` -- depending on the setup it may throw.

Can you enable DEBUG logging for `org.eclipse.jetty`?

**Comment by poutsma** [comment] 2023-07-24 12:01
> Another difference is that we create the string from all the bytes, while in your case you may have a split UTF-8 sequence when you try to decode the bytes into a `CharBuffer` -- depending on the setup it may throw.

Yeah, but in that case I would expect an exception signal, and not the lack of a completion signal. Also, I think that for `https://example.com`, the response is small enough to fit in a single buffer, so split multi-byte characters is not a concern.

> Can you enable DEBUG logging for `org.eclipse.jetty`?

[Here is the log output for the above sample](https://github.com/jetty-project/jetty-reactive-httpclient/files/12145536/jetty-reactive-client-issue.txt).

**Comment by poutsma** [comment] 2023-07-24 14:02
Another difference that might be relevant is that a `Flux` requests the maximum amount of items, whereas `BufferingProcessor` request one at a time.

**Comment by sbordet** [comment] 2023-07-24 14:43
@poutsma we were able to reproduce, standby for a fix.

**Comment by sbordet** [comment] 2023-07-24 20:49
@poutsma I released 4.0.0.beta1 with the fixes for the issue you reported here.
Let us know if it works for you.

**Comment by poutsma** [comment] 2023-07-25 08:33
@sbordet 4.0.0.beta1 resolved the issue, and I am seeing completion signals now. Good job!

In fact, all the client-related tests succeed now, but this is using the same buffer copying strategy that we had in 6.0. Now that the tests are green, I can work on making it more efficient, by supporting Jetty's `Retainable` through our data buffer abstraction.

**Comment by poutsma** [comment] 2023-07-26 10:58
I also managed to wrap up support for `Retainable`, see [here](https://github.com/poutsma/spring-framework/blob/a766eee05e3124eaa179f7ab691afb54b4a148eb/spring-web/src/main/java/org/springframework/http/client/reactive/JettyClientHttpConnector.java#L148).

With that, I think that our client-side support for Jetty 12 is complete. On the server-side, we are still investigating test failures related to async servlet read- and write listeners.

Note that I will be on vacation for a while, but—if necessary—will get back to you when I return.

**Comment by lorban** [comment] 2023-07-27 09:42
@poutsma thank you for the feedback. I believe this issue can be closed since we have a functional `jetty-reactive-httpclient` for Jetty 12.

If you encounter new problems or have any other feedback, do not hesitate to get back in touch.

**Closed as completed by lorban** 2023-07-27 09:42 UTC
